name: Dart CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    
    container:
      image:  google/dart:latest
    
    steps:
    - uses: actions/checkout@v1
    - name : x
      run: apt-get install lib32z1 lib32ncurses5 libbz2-1.0:i386 lib32stdc++6
    - name: Install dependencies
      run: flutter pub get
    - name: Run tests
      run: flutter pub run test
